name: Project Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: List Directory Structure
      run: |
        echo "Current directory structure:"
        ls -R
        pwd

    - name: Verify Project Configuration
      run: |
        echo "Checking project structure..."
        
        # Check for source directory
        if [ ! -d "src/player" ]; then
          echo "Error: src/player directory not found"
          exit 1
        fi
        
        # Check for main module file
        if [ -f "src/player/tt_um_audio_player.v" ]; then
          echo "Found main module in src/player directory"
        else
          echo "Error: Could not find tt_um_audio_player.v in src/player directory"
          exit 1
        fi
    
    - name: Setup Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog

    - name: Simulation
      if: success()
      run: |
        # Create build directory
        mkdir -p build
        
        # Compile Verilog files
        iverilog -o build/sim src/player/*.v
        
    - name: Upload Configuration
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: project-config
        path: |
          *.yaml
          *.yml
        retention-days: 5

    - name: Upload Source Files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: verilog-sources
        path: |
          src/player/*.v
        retention-days: 5

    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          build/
          *.out
          *.vcd
        retention-days: 5
